### ISSUE TITLE
Fork/PR todo list

### ISSUE THREAD

**Issue by duckcantcode** [duckfromdiscord/maloja#11]
- [x] Images alongside scrobbles (now includes album and track instead of only one)
- [ ] Identifiers (Spotify, MBID, etc all stored together - https://github.com/krateng/maloja/issues/249)
- [ ] Deezer import (https://github.com/krateng/maloja/discussions/383)

**Comment by cheesetosti** [comment]
Still relevant?
